// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `create_controller`, `create_environment`, `create_host_window`, `html_to_pdf`, `navigate_and_wait`, `print_to_pdf`, `render_inner`, `render`, `wndproc`

/// Run the whole thing on a FRESH thread: WebView2 needs a COM STA apartment
/// with a message pump, but the FRB worker thread we're invoked on may
/// already be COM-MTA (an STA init there would fail with RPC_E_CHANGED_MODE).
/// A brand-new thread has no apartment yet, so STA init always succeeds.
Future<Uint8List?> run({required String html}) =>
    RustLib.instance.api.crateApiPdfWinRun(html: html);
