import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:mica_flutter/main.dart';
import 'package:mica_flutter/editor/editor.dart';
import 'package:mica_flutter/l10n/app_localizations.dart';

DocumentBootstrap titleBootstrap(String title, {String id = 'page-a'}) =>
    DocumentBootstrap.fromJson({
      'document': {
        'id': id,
        'workspace_id': 'workspace',
        'root_block_id': 'root',
        'current_seq': 0,
        'created_by': 'user',
        'created_at': '2026-09-27T00:00:00Z',
        'updated_at': '2026-09-27T00:00:00Z',
      },
      'view': {
        'id': id,
        'parent_view_id': null,
        'object_id': id,
        'object_type': 'document',
        'name': title,
        'position': '0',
      },
      'snapshot': {
        'version_seq': 0,
        'schema_version': 1,
        'payload': {
          'schema_version': 1,
          'root_block_id': 'root',
          'blocks': [
            {
              'id': 'root',
              'type': 'page',
              'text': '',
              'data': {'title': title},
              'children': ['body'],
            },
            {'id': 'body', 'type': 'paragraph', 'text': '正文', 'children': []},
          ],
        },
      },
    });

// Exercise the real title field and its debounce with an inert host: the
// workspace has many unrelated callbacks, none of which this test invokes.
Widget titleWorkspace(
  DocumentBootstrap bootstrap,
  Future<bool> Function(DocumentView, String) onRename, {
  String? message,
  List<DocumentView>? views,
  List<WorkspaceEntry> entries = const [],
  Future<void> Function(List<WorkspaceEntry>)? onReorderWorkspaces,
  Future<void> Function(String?, List<DocumentView>)? onReorderViews,
}) => MaterialApp(
  locale: const Locale('zh'),
  localizationsDelegates: AppLocalizations.localizationsDelegates,
  supportedLocales: AppLocalizations.supportedLocales,
  home: Scaffold(
    body: WorkspaceView(
      apiBase: Uri.parse('http://localhost'),
      onChangeAvatar: null,
      onRemoveAvatar: null,
      onReplyComment: (_, _) async {},
      onSetCommentResolved: (_, _) async {},
      onDeleteCommentThread: (_) async {},
      onFocusCommentThread: (_) {},
      session: null,
      entries: entries,
      activeOrigin: 'local',
      selectedRef: null,
      onSelectEntry: (_) async {},
      onRenameEntry: (_, _) async {},
      onDeleteEntry: (_) async {},
      onExportEntryZip: (_) async => Uint8List(0),
      onImportTreeIntoEntry: (_, _, {sourceName, container}) async {},
      onImportTreeIntoFolder: (_, _, {sourceName, container}) async {},
      onReorderWorkspaces: onReorderWorkspaces ?? (_) async {},
      cloudOriginLabel: 'Test',
      onSignIn: null,
      localAvailable: true,
      isBusy: false,
      onRefresh: () {},
      onSignOut: () {},
      workspaces: const [
        Workspace(id: 'workspace', name: '测试', ownerId: 'user', role: 'owner'),
      ],
      selectedWorkspace: const Workspace(
        id: 'workspace',
        name: '测试',
        ownerId: 'user',
        role: 'owner',
      ),
      members: const [],
      views: views ?? [bootstrap.view],
      selectedView: bootstrap.view,
      selectedBootstrap: bootstrap,
      selectedMarkdown: null,
      presence: const [],
      message: message,
      onSelectWorkspace: (_) async {},
      onCreateWorkspace: (_) async {},
      onRenameWorkspace: (_, _) async {},
      onDeleteWorkspace: (_) async {},
      onCreateDocument: (_) async => null,
      onCreateChildDocument: (_, _) async => null,
      onCreateFolder: (_) async => null,
      onCreateChildFolder: (_, _) async => null,
      onReorderViews: onReorderViews ?? (_, _) async {},
      onLoadTrash: () async => [],
      onRestoreView: (_) async {},
      onPurgeView: (_) async {},
      onSelectView: (_) async {},
      onRenameView: onRename,
      onDeleteView: (_) async {},
      onDeleteViews: (_) async {},
      onCloneView: (_) async {},
      onUpdateRootBlockText: (_) async {},
      onAddBlock: (_, _) async {},
      onUpdateBlock: (_, _, _) async {},
      onDeleteBlock: (_) async {},
      onMoveBlock: (_, _) async {},
      onApplyOperations: (_) async {},
      onUploadImage: (_, _, _) async => null,
      onImportImageUrl: (_) async => null,
      onLoadImageBytes: (_) async => null,
      onResolveImageUrls: (_) async => {},
      onAiStream: (_, {system}) => const Stream.empty(),
      onAiNewPage: (_) async {},
      onAiCurrentPage: null,
      onAiNewWorkspace: (_) async {},
      onLoadAiSettings: null,
      onLoadImportHistory: null,
      onListAiModels: null,
      onSaveAiSettings: null,
      onDeleteAiProvider: null,
      userName: 'Test',
      userEmail: '',
      onUpdateProfile: null,
      onChangePassword: null,
      onDeleteAccount: null,
      onSwitchWorld: () {},
      onRemoveServer: (_) async {},
      appearance: const EditorAppearance(),
      pageWidth: 800,
      reHostImages: false,
      onReHostImagesChanged: (_) {},
      showFormatBar: false,
      onShowFormatBarChanged: (_) {},
      showPageTitle: true,
      onShowPageTitleChanged: (_) {},
      showAi: false,
      aiEnabled: false,
      onAiEnabledChanged: (_) {},
      onAppearanceChanged: (_, _) {},
      onOpenSearchResult: (_) async {},
      onExportPageZip: () async => Uint8List(0),
      onExportPage: (_) async =>
          (bytes: Uint8List(0), name: 'test', mime: 'text/plain'),
      onCopyPageMarkdown: () async => '',
      onExportPageHtml: (_) async => '',
      onExportPagePdf: (_) async => null,
      onImportMarkdown: (_, _) async {},
      onExportWorkspaceZip: (_) async => Uint8List(0),
      onImportWorkspaceZip: null,
      onImportWorkspaceTreeInto: (_, _) async {},
    ),
  ),
);
