// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MicaDocument>>
abstract class MicaDocument implements RustOpaqueInterface {
  void deleteBlock({required String id, required bool bringChildren});

  /// Encode the full document state (the base snapshot to persist locally).
  Uint8List encodeState();

  /// Build a document from a root id and a JSON array of blocks.
  static MicaDocument fromBlocksJson({
    required String rootId,
    required String blocksJson,
  }) => RustLib.instance.api.crateApiDocumentMicaDocumentFromBlocksJson(
    rootId: rootId,
    blocksJson: blocksJson,
  );

  /// Rebuild from an encoded yrs state (the local snapshot). Returns null if
  /// the bytes don't decode.
  static MicaDocument? fromState({required List<int> bytes}) =>
      RustLib.instance.api.crateApiDocumentMicaDocumentFromState(bytes: bytes);

  void insertBlockJson({
    required String parentId,
    required int index,
    required String blockJson,
  });

  void joinIntoPrev({required String id});

  void moveBlock({
    required String id,
    required String newParent,
    required int index,
  });

  String rootBlockId();

  void setBlockDataJson({required String id, required String dataJson});

  void splitBlock({
    required String id,
    required int at,
    required String newId,
    required String newKind,
  });

  void textDelete({required String id, required int at, required int len});

  void textFormat({
    required String id,
    required int start,
    required int end,
    required String ty,
    String? href,
    String? title,
  });

  void textInsert({required String id, required int at, required String text});

  /// The document as a JSON array of blocks (tree order).
  String toBlocksJson();

  /// Mirror the editor's coarse `update_block` op: apply any subset of
  /// kind/text/data to a block in one call. Inline marks travel *inside* the
  /// editor's `data` (`data["marks"]`) — when `text` is given they are applied
  /// to the (replaced) text as yrs formatting; `set_block_data` then stores the
  /// non-marks props. This is the single chokepoint the desktop op stream funnels
  /// through, so the on-device yrs doc tracks every edit (P2-M3).
  void updateBlock({
    required String id,
    String? kind,
    String? text,
    String? dataJson,
  });

  void updateBlockKind({required String id, required String kind});
}
