// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `safe_base`, `snapshot`, `unique_asset_name`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MicaDocument>>
abstract class MicaDocument implements RustOpaqueInterface {
  /// Merge a remote yrs update into this doc (CRDT merge). Returns false if the
  /// bytes don't decode (caller should resync rather than trust local state).
  bool applyUpdate({required List<int> update});

  void deleteBlock({required String id, required bool bringChildren});

  /// The minimal update carrying everything added since `state_vector` was
  /// taken — the bytes to push to the cloud. Empty on a malformed vector.
  Uint8List encodeDiffSince({required List<int> stateVector});

  /// Encode the full document state (the base snapshot to persist locally).
  Uint8List encodeState();

  /// Export this page as a self-contained HTML document, through the same Rust
  /// engine the server uses — so a LOCAL page's export matches a cloud page's
  /// byte-for-byte. `image_srcs` maps image `file_id`s to `data:` URIs the Dart
  /// side has already read from the on-device blob CAS; images with no entry
  /// keep their url. Local export otherwise had no path (the ZIP/Markdown
  /// exports are server endpoints), so this also closes that gap.
  String exportHtml({
    required String title,
    required Map<String, String> imageSrcs,
    required int contentWidth,
  });

  /// Export this page's body as Markdown through the SAME engine the cloud uses
  /// (`mica_markdown::export_markdown`), so a local page's `.md` matches a cloud
  /// page's byte-for-byte. Image blocks keep their stored ref — use
  /// [`MicaDocument::export_markdown_zip`] when bundling image bytes. Closes the
  /// local-page md-export gap (previously only HTML/PDF existed locally).
  String exportMarkdown();

  /// Export this page as a portable ZIP (`<base>.md` + `assets/<name>` image
  /// bytes), byte-compatible with the cloud page ZIP export: same naming +
  /// dedup + Markdown rewrite via `export_markdown_with_assets`. [`assets`]
  /// supplies the on-device blob bytes per `file_id` (Dart reads the local
  /// CAS); external-URL images are left untouched.
  Uint8List exportMarkdownZip({
    required String base,
    required List<ZipAsset> assets,
  });

  /// Build a document from a root id and a JSON array of blocks.
  static MicaDocument fromBlocksJson({
    required String rootId,
    required String blocksJson,
  }) => RustLib.instance.api.crateApiDocumentMicaDocumentFromBlocksJson(
    rootId: rootId,
    blocksJson: blocksJson,
  );

  /// Build a document by parsing Markdown with the authoritative engine
  /// (CommonMark + GFM). Used by local vault import (S-tier): the file stays the
  /// user's, parsing stays in Rust (and round-trips with `export_markdown`). A
  /// fresh root id is minted; `mica_markdown::Block` mirrors `mica_core::Block`
  /// field-for-field, so no schema translation is needed.
  static MicaDocument fromMarkdown({required String markdown}) => RustLib
      .instance
      .api
      .crateApiDocumentMicaDocumentFromMarkdown(markdown: markdown);

  /// Rebuild from an encoded yrs state (the local snapshot). Returns null if
  /// the bytes don't decode.
  static MicaDocument? fromState({required List<int> bytes}) =>
      RustLib.instance.api.crateApiDocumentMicaDocumentFromState(bytes: bytes);

  /// Like [`Self::from_state`] but pins the yrs actor to this device's stable
  /// `client_id` (from the local store identity) — so all of a device's edits
  /// share one actor across sessions, which cloud sync (P2-M4.5) relies on.
  static MicaDocument? fromStateWithClientId({
    required List<int> bytes,
    required BigInt clientId,
  }) => RustLib.instance.api.crateApiDocumentMicaDocumentFromStateWithClientId(
    bytes: bytes,
    clientId: clientId,
  );

  void insertBlockJson({
    required String parentId,
    required int index,
    required String blockJson,
  });

  void joinIntoPrev({required String id});

  void moveBlock({
    required String id,
    required String newParent,
    required int index,
  });

  String rootBlockId();

  void setBlockDataJson({required String id, required String dataJson});

  void splitBlock({
    required String id,
    required int at,
    required String newId,
    required String newKind,
  });

  /// This replica's state vector — capture it before an edit batch, then
  /// [`Self::encode_diff_since`] after to get just that batch's update to push.
  Uint8List stateVector();

  void textDelete({required String id, required int at, required int len});

  void textFormat({
    required String id,
    required int start,
    required int end,
    required String ty,
    String? href,
    String? title,
  });

  void textInsert({required String id, required int at, required String text});

  /// The document as a JSON array of blocks (tree order).
  String toBlocksJson();

  /// Mirror the editor's coarse `update_block` op: apply any subset of
  /// kind/text/data to a block in one call. Inline marks travel *inside* the
  /// editor's `data` (`data["marks"]`) — when `text` is given they are applied
  /// to the (replaced) text as yrs formatting; `set_block_data` then stores the
  /// non-marks props. This is the single chokepoint the desktop op stream funnels
  /// through, so the on-device yrs doc tracks every edit (P2-M3).
  void updateBlock({
    required String id,
    String? kind,
    String? text,
    String? dataJson,
  });

  void updateBlockKind({required String id, required String kind});
}

/// One on-device image blob to bundle into a page ZIP export: the block's
/// `file_id` plus the bytes Dart read from the local blob CAS.
class ZipAsset {
  final String fileId;
  final Uint8List bytes;

  const ZipAsset({required this.fileId, required this.bytes});

  @override
  int get hashCode => fileId.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZipAsset &&
          runtimeType == other.runtimeType &&
          fileId == other.fileId &&
          bytes == other.bytes;
}
