// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Render `html` (a complete, self-contained HTML document) to PDF bytes, or
/// `None` if unsupported on this platform / the runtime is unavailable / print
/// failed. Async by default (FRB runs it off the Dart isolate); internally it
/// hosts an off-screen WebView2 on a dedicated STA thread.
Future<Uint8List?> exportPdf({required String html}) =>
    RustLib.instance.api.crateApiPdfExportPdf(html: html);
