// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Render Mermaid `source` to a self-contained SVG string, or `None` on a
/// syntax / render error. Async by default (runs off the Dart isolate); the
/// editor rasterizes the returned SVG for its inline preview.
Future<String?> renderMermaidSvg({required String source}) =>
    RustLib.instance.api.crateApiRenderRenderMermaidSvg(source: source);
