// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'document.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MicaStore>>
abstract class MicaStore implements RustOpaqueInterface {
  /// Append a yrs `update` to `doc_id`'s local log; returns its new monotonic
  /// `clock` (0 on error). Pair with [`Self::save_doc`] as the base.
  PlatformInt64 appendUpdate({
    required String docId,
    required List<int> update,
  });

  /// Save the doc's current base as a recovery checkpoint (§10). Call at safe
  /// points (doc open/close) so a later corruption can be rolled back.
  void checkpointDoc({required String docId});

  /// The stable yrs client id new/loaded documents should use.
  BigInt clientId();

  void deleteDoc({required String docId});

  /// Delete a workspace and all its view rows (delete documents separately).
  void deleteWorkspace({required String id});

  /// The persisted device id.
  String deviceId();

  /// Ids of all stored documents (sorted).
  List<String> listDocs();

  /// All views (including trashed) for `origin` ("local" or a server URL),
  /// ordered by position. The client builds the tree from `parent_id` and
  /// filters trash.
  List<LocalView> listViews({required String origin});

  /// All workspaces for `origin` ("local" or a server URL), ordered by position.
  List<LocalWorkspace> listWorkspaces({required String origin});

  /// Load a document by id, decoded with this device's stable client id, or
  /// null if there's no such document.
  MicaDocument? loadDoc({required String docId});

  /// Open (creating if needed) the local store at `path`. Returns null on
  /// failure (e.g. an unwritable path).
  static MicaStore? open({required String path}) =>
      RustLib.instance.api.crateApiStoreMicaStoreOpen(path: path);

  /// Permanently remove a view row (delete its document via [`Self::delete_doc`]).
  void purgeView({required String id});

  /// Restore a doc from its last checkpoint, returning the recovered document
  /// (null if there's no checkpoint).
  MicaDocument? rollbackDoc({required String docId});

  /// Persist a document under `doc_id` (full snapshot).
  void saveDoc({required String docId, required MicaDocument doc});

  /// Upsert a view (create / rename / move / trash-toggle).
  void saveView({required LocalView view});

  /// Upsert a workspace (create / rename / reorder).
  void saveWorkspace({required LocalWorkspace workspace});

  /// Persist this doc's sync progress.
  void setSyncCursor({required String docId, required SyncCursor cursor});

  /// Fold the update log into the base snapshot and truncate it (compaction),
  /// so the log doesn't grow without bound. Safe no-op if the doc is absent.
  void squash({required String docId});

  /// This doc's sync progress (0/0 if it has never synced).
  SyncCursor syncCursor({required String docId});

  /// Log entries with `clock > after`, ordered — the un-pushed outbox when
  /// `after = sync_cursor.pushed_clock`, or catch-up from a known clock.
  List<DocUpdate> updatesAfter({
    required String docId,
    required PlatformInt64 after,
  });
}

/// One entry from a doc's local update log: its monotonic `clock` and the yrs
/// update bytes. `updates_after(pushed_clock)` yields the un-pushed outbox.
class DocUpdate {
  final PlatformInt64 clock;
  final Uint8List payload;

  const DocUpdate({required this.clock, required this.payload});

  @override
  int get hashCode => clock.hashCode ^ payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocUpdate &&
          runtimeType == other.runtimeType &&
          clock == other.clock &&
          payload == other.payload;
}

/// A page-tree node mirrored to Dart (P2-M3) — the local mirror of the client's
/// `DocumentView`. `object_id` is the document's `doc_id`.
class LocalView {
  final String id;
  final String workspaceId;
  final String? parentId;
  final String objectId;
  final String name;
  final String position;
  final bool trashed;

  /// Provenance: "local" for on-device pages, or a server URL for a cloud
  /// page mirrored for offline nav. `list_views` filters by this.
  final String origin;

  const LocalView({
    required this.id,
    required this.workspaceId,
    this.parentId,
    required this.objectId,
    required this.name,
    required this.position,
    required this.trashed,
    required this.origin,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      workspaceId.hashCode ^
      parentId.hashCode ^
      objectId.hashCode ^
      name.hashCode ^
      position.hashCode ^
      trashed.hashCode ^
      origin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          workspaceId == other.workspaceId &&
          parentId == other.parentId &&
          objectId == other.objectId &&
          name == other.name &&
          position == other.position &&
          trashed == other.trashed &&
          origin == other.origin;
}

/// A local workspace mirrored to Dart (P2-M3).
class LocalWorkspace {
  final String id;
  final String name;
  final String position;

  /// Provenance: "local" or a server URL — same scoping as [`LocalView`].
  final String origin;

  const LocalWorkspace({
    required this.id,
    required this.name,
    required this.position,
    required this.origin,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ position.hashCode ^ origin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalWorkspace &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          position == other.position &&
          origin == other.origin;
}

/// A document's sync progress against the cloud update stream (P2 local-first).
/// Persisted per-doc so a locally-stored replica knows where to resume: pull the
/// cloud tail after `last_synced_rid`, push local log entries past `pushed_clock`.
class SyncCursor {
  /// Highest cloud stream id (`rid`) this device has pulled and applied.
  final PlatformInt64 lastSyncedRid;

  /// Highest local update `clock` this device has pushed to the cloud.
  final PlatformInt64 pushedClock;

  const SyncCursor({required this.lastSyncedRid, required this.pushedClock});

  @override
  int get hashCode => lastSyncedRid.hashCode ^ pushedClock.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncCursor &&
          runtimeType == other.runtimeType &&
          lastSyncedRid == other.lastSyncedRid &&
          pushedClock == other.pushedClock;
}
