// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'document.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clone_view_row`, `dedup_sibling_name`, `next_position`, `next_workspace_position`, `parent_accepts_children`, `set_trashed`, `store`, `subtree_ids`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MicaStore>>
abstract class MicaStore implements RustOpaqueInterface {
  /// Durably append a REMOTE update and advance `last_synced_rid` in the same
  /// transaction (P4-1) — the persisted cursor can never point past an update
  /// that isn't on disk. Idempotent per `(doc_id, rid)`. Returns false when
  /// the write FAILED (busy/full/io) so the caller can self-heal by writing a
  /// base snapshot from the live in-memory doc — a swallowed failure here plus
  /// a later disk-rebuilding compact would silently lose the update (P4-1
  /// review CRITICAL).
  bool appendRemoteUpdate({
    required String docId,
    required PlatformInt64 rid,
    required List<int> update,
  });

  /// Batch variant: one transaction (one journal sync) for a whole
  /// `sync.updates` catch-up array. Parallel lists (rids[i] ↔ updates[i]).
  bool appendRemoteUpdates({
    required String docId,
    required Int64List rids,
    required List<Uint8List> updates,
  });

  /// Append a yrs `update` to `doc_id`'s local log; returns its new monotonic
  /// `clock` (0 on error). Pair with [`Self::save_doc`] as the base.
  PlatformInt64 appendUpdate({
    required String docId,
    required List<int> update,
  });

  /// Index documents stored before the text projection existed. Returns how
  /// many it did; the caller loops until it returns 0.
  ///
  /// Batched and caller-driven on purpose — see the store-side note: a big
  /// library must not turn the first launch after an update into a stall.
  Future<int> backfillSearchIndex({required int limit});

  /// The pages that link TO `view_id` — the local backlinks panel.
  ///
  /// NOT `#[frb(sync)]`, same reason as `search_local`: this runs on every page
  /// open, and the panel is explicitly allowed to land a frame or two late
  /// rather than hold up the document that the user actually asked for.
  Future<List<LocalBacklink>> backlinksLocal({required String viewId});

  /// Save the doc's current base as a recovery checkpoint (§10). Call at safe
  /// points (doc open/close) so a later corruption can be rolled back.
  void checkpointDoc({required String docId});

  /// The stable yrs client id new/loaded documents should use.
  BigInt clientId();

  /// Duplicate `view_id` and everything under it, beside the original.
  ///
  /// The WHOLE operation, not a helper: subtree walk, fresh ids, doc copies,
  /// sibling-name dedup and positioning all happen here. That is the point —
  /// moving a leaf helper across the bridge would leave the tree rules
  /// duplicated and pay a crossing per node; moving the operation deletes the
  /// Dart copy outright. Mirrors `export_folder_zip` above, the composite
  /// that was already de-duplicated this way.
  ///
  /// Returns `None` when the view is gone.
  CloneViewResult? cloneView({
    required String viewId,
    required String rootName,
  });

  /// Fold the log into the base and clear it — for a document with NO cloud
  /// counterpart, where [`Self::squash`] and [`Self::trim_updates_through`]
  /// are both permanent no-ops (they are bounded by `pushed_clock`, which
  /// stays 0 forever without a server). Returns whether it compacted; it
  /// refuses on any doc showing evidence of sync, so the offline backend
  /// cannot accidentally drop an un-pushed outbox.
  bool compactLocal({required String docId});

  /// Pin the current saved state as a NAMED version (never auto-pruned). Null
  /// if the document has no saved snapshot yet.
  LocalVersion? createLocalVersion({
    required String docId,
    required String label,
  });

  /// Create a page or folder row under `parent_id` and return its id.
  ///
  /// Serves both kinds: a document passes the `object_id` its freshly-created
  /// doc got, a folder passes a placeholder (it owns no document). Position
  /// comes from [`Self::next_position`], so a page created here and a page
  /// cloned by [`Self::clone_view`] land by the same rule.
  String createView({
    required String workspaceId,
    String? parentId,
    required String objectId,
    required String name,
    required String objectType,
  });

  /// Create a local workspace and return its id.
  String createWorkspace({required String name});

  void deleteDoc({required String docId});

  /// Delete one `origin`'s workspace and all its view rows (delete documents
  /// separately). Origin-scoped (v4 composite PK).
  void deleteWorkspace({required String origin, required String id});

  /// Delete a workspace, its views and their documents. Returns false — and
  /// changes nothing — when it is the last one.
  ///
  /// Both rules live here rather than in the caller. "Keep at least one
  /// workspace" was a UI-side check, so any other path into delete could
  /// leave the device with none and nowhere to put a page; and dropping the
  /// workspace row without its documents left orphaned blobs that nothing
  /// would ever reach again.
  bool deleteWorkspaceCascade({required String id});

  /// The persisted device id.
  String deviceId();

  /// Export a folder's subtree (`folder_id = Some`) — or the whole workspace
  /// (`None`) — as a Markdown ZIP, through the SAME shared builder the cloud
  /// uses (`mica_interchange::build_markdown_tree_zip`), so a local export is
  /// the same format as a cloud one and the export→import round-trip holds. The
  /// store supplies views + document payloads; [`images`] supplies the blob
  /// bytes per `file_id` (Dart reads the on-device CAS). Closes the last local
  /// folder-export gap (was cloud-only).
  Uint8List exportFolderZip({
    required String workspaceId,
    String? folderId,
    required List<FolderExportImage> images,
  });

  /// The page-link graph for the graph view.
  ///
  /// NOT `#[frb(sync)]`: it reads every view and every link row. The view has
  /// its own loading state; the frame does not.
  Future<LocalGraph> graphLocal();

  /// Ids of all stored documents (sorted).
  List<String> listDocs();

  /// The document's version timeline, newest first — auto snapshots (captured
  /// on a cadence by `save_doc`) and named checkpoints interleaved.
  List<LocalVersion> listLocalVersions({required String docId});

  /// All views (including trashed) for `origin` ("local" or a server URL),
  /// ordered by position. The client builds the tree from `parent_id` and
  /// filters trash.
  List<LocalView> listViews({required String origin});

  /// All workspaces for `origin` ("local" or a server URL), ordered by position.
  List<LocalWorkspace> listWorkspaces({required String origin});

  /// Load a document by id, decoded with this device's stable client id.
  /// Returns `null` when there is simply no such document; returns `Err`
  /// (throws in Dart) when the stored snapshot is PRESENT but corrupt/
  /// unreadable. The two MUST stay distinct: the caller must not treat a
  /// corrupt doc as "new" and seed a blank page over it, which would launder
  /// the corruption and overwrite the recovery checkpoint (see
  /// `LocalDocBackend.open`). Previously `.ok()??` collapsed both to null.
  MicaDocument? loadDoc({required String docId});

  /// Decode a version into a THROWAWAY document for read-only preview (never
  /// the live doc). Null if the version isn't found. The caller renders it with
  /// `to_blocks_json()` / `root_block_id()` in a read-only editor.
  MicaDocument? localVersionDoc({
    required String docId,
    required String versionId,
  });

  /// (local outbox rows, remote log rows) — compaction-trigger bookkeeping.
  (PlatformInt64, PlatformInt64) logSizes({required String docId});

  /// Open (creating if needed) the local store at `path`. Returns null on
  /// failure (e.g. an unwritable path).
  static MicaStore? open({required String path}) =>
      RustLib.instance.api.crateApiStoreMicaStoreOpen(path: path);

  /// Permanently remove one `origin`'s view row (delete its document via
  /// [`Self::delete_doc`]). Origin-scoped — can never reach across the
  /// local/cloud namespaces (v4 composite PK).
  void purgeView({required String origin, required String id});

  /// Permanently remove `view_id` and its subtree, documents included.
  /// Returns the affected ids. There is no undo past this point.
  List<String> purgeViewSubtree({required String viewId});

  /// Rename a workspace, KEEPING its position and role.
  ///
  /// The Dart version had to read the row back to preserve `position`,
  /// because the only primitive was a whole-row upsert — and when the read
  /// missed it invented `0000000010`, which can collide with a real
  /// neighbour. Doing it here means a missing row is simply a no-op.
  void renameWorkspace({required String id, required String name});

  /// Renumber `ordered_ids` as consecutive children of `parent_id`.
  ///
  /// Positions restart at 10 and step by ten, matching
  /// [`Self::next_position`] so a later insert still lands after them. Rows
  /// already in the right place are left alone — an untouched row is one less
  /// write and one less sync update. Reparenting is part of the same move:
  /// dragging into another folder changes both.
  void reorderViews({String? parentId, required List<String> orderedIds});

  /// Renumber workspaces to match `ordered_ids` (drag-reorder), same
  /// step-of-ten scheme as [`Self::reorder_views`].
  void reorderWorkspaces({required List<String> orderedIds});

  /// Restore the document to a version, returning the recovered doc (null if
  /// the version isn't found). The pre-restore state is kept as an auto version
  /// so the restore is itself undoable.
  MicaDocument? restoreLocalVersion({
    required String docId,
    required String versionId,
  });

  /// Bring `view_id` and the subtree trashed with it back out of the bin.
  ///
  /// If the restored ROOT's parent is no longer a live view, the root is
  /// lifted to the top level — restoring into a trashed parent would leave it
  /// invisible with no way back. Mirrors the server's `restore_view`.
  List<String> restoreViewSubtree({required String viewId});

  /// Restore a doc from its last checkpoint, returning the recovered document
  /// (null if there's no checkpoint).
  MicaDocument? rollbackDoc({required String docId});

  /// Persist a document under `doc_id` (full snapshot).
  void saveDoc({required String docId, required MicaDocument doc});

  /// Upsert a view (create / rename / move / trash-toggle).
  bool saveView({required LocalView view});

  /// Upsert a workspace (create / rename / reorder).
  void saveWorkspace({required LocalWorkspace workspace});

  /// Search this device's documents by title and body.
  ///
  /// NOT `#[frb(sync)]`: it touches every indexed document, and the one thing a
  /// search box must never do is freeze the frame you are typing into.
  Future<List<LocalSearchHit>> searchLocal({
    required String query,
    required int limit,
  });

  /// Persist this doc's sync progress.
  void setSyncCursor({required String docId, required SyncCursor cursor});

  /// Fold the update log into the base snapshot and truncate it (compaction),
  /// so the log doesn't grow without bound. Safe no-op if the doc is absent.
  void squash({required String docId});

  /// This doc's sync progress (0/0 if it has never synced).
  SyncCursor syncCursor({required String docId});

  /// Move `view_id` and its whole subtree to the recycle bin. Returns the
  /// affected ids so the caller can close an editor that was inside it.
  ///
  /// A folder carries its children: trashing one must trash the subtree, or
  /// the children survive as orphans pointing at a trashed parent.
  List<String> trashViewSubtree({required String viewId});

  /// Drop acked outbox entries (`clock ≤ up_to_clock`, i.e. `pushed_clock`),
  /// bounding the append-log while leaving the un-pushed tail intact. The base
  /// snapshot already folds these, so reads are unchanged; the clock stays
  /// monotonic across this so no future clock is reused below the trim.
  void trimUpdatesThrough({
    required String docId,
    required PlatformInt64 upToClock,
  });

  /// Log entries with `clock > after`, ordered — the un-pushed outbox when
  /// `after = sync_cursor.pushed_clock`, or catch-up from a known clock.
  List<DocUpdate> updatesAfter({
    required String docId,
    required PlatformInt64 after,
  });
}

/// What [`MicaStore::clone_view`] produced: where the copy landed, the name it
/// settled on after dedup, and how many documents were actually copied
/// (folders and doc-less views do not count).
class CloneViewResult {
  final String rootViewId;
  final String newName;
  final int docs;

  const CloneViewResult({
    required this.rootViewId,
    required this.newName,
    required this.docs,
  });

  @override
  int get hashCode => rootViewId.hashCode ^ newName.hashCode ^ docs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloneViewResult &&
          runtimeType == other.runtimeType &&
          rootViewId == other.rootViewId &&
          newName == other.newName &&
          docs == other.docs;
}

/// One entry from a doc's local update log: its monotonic `clock` and the yrs
/// update bytes. `updates_after(pushed_clock)` yields the un-pushed outbox.
class DocUpdate {
  final PlatformInt64 clock;
  final Uint8List payload;

  const DocUpdate({required this.clock, required this.payload});

  @override
  int get hashCode => clock.hashCode ^ payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocUpdate &&
          runtimeType == other.runtimeType &&
          clock == other.clock &&
          payload == other.payload;
}

/// One on-device image blob for a folder-tree ZIP export: the referencing
/// block's `file_id`, its display name, and the bytes Dart read from the local
/// blob CAS. The store reads views + document payloads itself; only blob bytes
/// (Dart-managed files) must be handed in.
class FolderExportImage {
  final String fileId;
  final String name;
  final Uint8List bytes;

  const FolderExportImage({
    required this.fileId,
    required this.name,
    required this.bytes,
  });

  @override
  int get hashCode => fileId.hashCode ^ name.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FolderExportImage &&
          runtimeType == other.runtimeType &&
          fileId == other.fileId &&
          name == other.name &&
          bytes == other.bytes;
}

/// One page that links TO the page being viewed. Same three fields the cloud's
/// `Backlink` carries, so the panel has one model for both worlds.
class LocalBacklink {
  final String viewId;
  final String objectId;
  final String name;

  const LocalBacklink({
    required this.viewId,
    required this.objectId,
    required this.name,
  });

  @override
  int get hashCode => viewId.hashCode ^ objectId.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalBacklink &&
          runtimeType == other.runtimeType &&
          viewId == other.viewId &&
          objectId == other.objectId &&
          name == other.name;
}

/// A local workspace mirrored to Dart (P2-M3).
/// The page-link graph of this device's workspace. Same shape the cloud's
/// `GET /workspaces/{id}/graph` returns, so the view has one model.
class LocalGraph {
  final List<LocalGraphNode> nodes;
  final List<LocalGraphEdge> edges;

  /// Live documents no link touches — a count, not nodes. See the store-side
  /// note: most pages in a real library link to nothing.
  final PlatformInt64 unlinked;

  const LocalGraph({
    required this.nodes,
    required this.edges,
    required this.unlinked,
  });

  @override
  int get hashCode => nodes.hashCode ^ edges.hashCode ^ unlinked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalGraph &&
          runtimeType == other.runtimeType &&
          nodes == other.nodes &&
          edges == other.edges &&
          unlinked == other.unlinked;
}

class LocalGraphEdge {
  final String source;
  final String target;

  const LocalGraphEdge({required this.source, required this.target});

  @override
  int get hashCode => source.hashCode ^ target.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalGraphEdge &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          target == other.target;
}

class LocalGraphNode {
  final String viewId;
  final String name;
  final PlatformInt64 degree;

  const LocalGraphNode({
    required this.viewId,
    required this.name,
    required this.degree,
  });

  @override
  int get hashCode => viewId.hashCode ^ name.hashCode ^ degree.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalGraphNode &&
          runtimeType == other.runtimeType &&
          viewId == other.viewId &&
          name == other.name &&
          degree == other.degree;
}

/// One local search hit. Same fields the cloud's `SearchResult` carries, so the
/// Dart side keeps one model for both worlds instead of branching on which world
/// it is in.
class LocalSearchHit {
  final String viewId;
  final String objectId;
  final String name;
  final String? parentViewId;
  final bool isFolder;
  final bool titleMatch;
  final String snippet;

  const LocalSearchHit({
    required this.viewId,
    required this.objectId,
    required this.name,
    this.parentViewId,
    required this.isFolder,
    required this.titleMatch,
    required this.snippet,
  });

  @override
  int get hashCode =>
      viewId.hashCode ^
      objectId.hashCode ^
      name.hashCode ^
      parentViewId.hashCode ^
      isFolder.hashCode ^
      titleMatch.hashCode ^
      snippet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalSearchHit &&
          runtimeType == other.runtimeType &&
          viewId == other.viewId &&
          objectId == other.objectId &&
          name == other.name &&
          parentViewId == other.parentViewId &&
          isFolder == other.isFolder &&
          titleMatch == other.titleMatch &&
          snippet == other.snippet;
}

/// One entry in a local page's version timeline, mirrored to Dart. `label` is
/// null for an auto snapshot, set for a named checkpoint; `created_at` is unix
/// millis.
class LocalVersion {
  final String id;
  final String? label;
  final PlatformInt64 createdAt;

  const LocalVersion({required this.id, this.label, required this.createdAt});

  @override
  int get hashCode => id.hashCode ^ label.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalVersion &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          createdAt == other.createdAt;
}

/// A page-tree node mirrored to Dart (P2-M3) — the local mirror of the client's
/// `DocumentView`. `object_id` is the document's `doc_id`.
class LocalView {
  final String id;
  final String workspaceId;
  final String? parentId;
  final String objectId;
  final String name;
  final String position;
  final bool trashed;

  /// Provenance: "local" for on-device pages, or a server URL for a cloud
  /// page mirrored for offline nav. `list_views` filters by this.
  final String origin;

  /// "document" (default) or "folder" (a pure container, no content).
  final String objectType;

  const LocalView({
    required this.id,
    required this.workspaceId,
    this.parentId,
    required this.objectId,
    required this.name,
    required this.position,
    required this.trashed,
    required this.origin,
    required this.objectType,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      workspaceId.hashCode ^
      parentId.hashCode ^
      objectId.hashCode ^
      name.hashCode ^
      position.hashCode ^
      trashed.hashCode ^
      origin.hashCode ^
      objectType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          workspaceId == other.workspaceId &&
          parentId == other.parentId &&
          objectId == other.objectId &&
          name == other.name &&
          position == other.position &&
          trashed == other.trashed &&
          origin == other.origin &&
          objectType == other.objectType;
}

class LocalWorkspace {
  final String id;
  final String name;
  final String position;

  /// Provenance: "local" or a server URL — same scoping as [`LocalView`].
  final String origin;

  /// The user's role in this workspace (mirrored from the server so offline
  /// editing knows whether it's allowed — P2d). Local workspaces: owner.
  final String role;

  const LocalWorkspace({
    required this.id,
    required this.name,
    required this.position,
    required this.origin,
    required this.role,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      position.hashCode ^
      origin.hashCode ^
      role.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalWorkspace &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          position == other.position &&
          origin == other.origin &&
          role == other.role;
}

/// A document's sync progress against the cloud update stream (P2 local-first).
/// Persisted per-doc so a locally-stored replica knows where to resume: pull the
/// cloud tail after `last_synced_rid`, push local log entries past `pushed_clock`.
class SyncCursor {
  /// Highest cloud stream id (`rid`) this device has pulled and applied.
  final PlatformInt64 lastSyncedRid;

  /// Highest local update `clock` this device has pushed to the cloud.
  final PlatformInt64 pushedClock;

  const SyncCursor({required this.lastSyncedRid, required this.pushedClock});

  @override
  int get hashCode => lastSyncedRid.hashCode ^ pushedClock.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncCursor &&
          runtimeType == other.runtimeType &&
          lastSyncedRid == other.lastSyncedRid &&
          pushedClock == other.pushedClock;
}
