// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Build a STORE (uncompressed) ZIP — the upload container for server-side
/// import. No compression on purpose: it goes straight to our own backend,
/// and md/images don't gain much anyway. UTF-8 name flag set.
Uint8List buildStoreZip({required List<StoreZipEntry> entries}) =>
    RustLib.instance.api.crateApiZipBuildStoreZip(entries: entries);

/// One file headed into the archive (folder/multi-file import packing).
class StoreZipEntry {
  final String name;
  final Uint8List bytes;

  const StoreZipEntry({required this.name, required this.bytes});

  @override
  int get hashCode => name.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoreZipEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          bytes == other.bytes;
}
