// Cross-engine byte floor for the STORE-ZIP encoder: the pure-Dart writer
// (web's implementation, lib/upload/zip_writer_dart.dart) must produce
// EXACTLY the bytes of the Rust `mica_interchange` writer (server + desktop
// FFI) for the shared fixture. The gold is generated by
// `GEN_GOLD=1 cargo test -p mica-interchange --test zip_gold`; the entry set
// below mirrors that test VERBATIM. A drift means an unopenable upload — if a
// format change is deliberate, change BOTH writers and the gold in one change.
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:mica_flutter/upload/archive_file.dart';
import 'package:mica_flutter/upload/zip_writer_dart.dart';

void main() {
  test('pure-Dart STORE zip matches the Rust gold byte-for-byte', () {
    final gold = File('../../crates/interchange/tests/fixtures/store_zip.gold');
    expect(gold.existsSync(), isTrue,
        reason: 'expected shared fixture at ${gold.absolute.path} — '
            'generate with GEN_GOLD=1 cargo test -p mica-interchange --test zip_gold');

    // Mirrors fixture_entries() in crates/interchange/tests/zip_gold.rs.
    final built = buildStoreZip([
      ArchiveFile('README.md', Uint8List.fromList('# Mica\n'.codeUnits)),
      ArchiveFile(
        '笔记/图 1.png',
        Uint8List.fromList([for (var b = 0; b <= 255; b++) b]),
      ),
      ArchiveFile('empty.txt', Uint8List(0)),
    ]);

    expect(built, gold.readAsBytesSync(),
        reason: 'STORE-ZIP bytes drifted between the Dart and Rust writers');
  });
}
