//! Explicit, one-time audit of objects created before the pending-upload ledger.
//! Normal GC only walks database rows; it must never scan the bucket on a timer.

use std::collections::HashSet;
use std::time::Duration;

use anyhow::{Context, bail};
use mica_app_core::store;
use mica_infra::storage::S3Config;
use serde_json::json;
use sqlx::PgPool;
use uuid::Uuid;

const PREFIX: &str = "workspaces/";
const PAGE_SIZE: u16 = 500;
const MAX_PAGE_BYTES: usize = 4 * 1024 * 1024;

#[derive(Debug, PartialEq, Eq)]
struct Page {
  keys: Vec<String>,
  next_token: Option<String>,
}

fn child_text<'a>(node: roxmltree::Node<'a, 'a>, name: &str) -> Option<&'a str> {
  node
    .children()
    .find(|child| child.is_element() && child.tag_name().name() == name)
    .and_then(|child| child.text())
}

fn parse_page(xml: &str, prefix: &str) -> anyhow::Result<Page> {
  let doc = roxmltree::Document::parse(xml).context("invalid ListObjectsV2 XML")?;
  let root = doc.root_element();
  if root.tag_name().name() != "ListBucketResult" {
    bail!("S3 returned an unexpected list response");
  }
  if child_text(root, "Prefix") != Some(prefix) {
    bail!("S3 list response has the wrong prefix");
  }
  let truncated = match child_text(root, "IsTruncated") {
    Some("true") => true,
    Some("false") => false,
    _ => bail!("S3 list response has no valid IsTruncated"),
  };
  let keys = root
    .children()
    .filter(|child| child.is_element() && child.tag_name().name() == "Contents")
    .map(|child| {
      child_text(child, "Key")
        .map(str::to_owned)
        .context("S3 item has no key")
    })
    .collect::<anyhow::Result<Vec<_>>>()?;
  if keys.len() > PAGE_SIZE as usize {
    bail!("S3 returned more objects than requested");
  }
  let next_token = child_text(root, "NextContinuationToken").map(str::to_owned);
  if truncated && next_token.as_deref().is_none_or(str::is_empty) {
    bail!("truncated S3 list response has no continuation token");
  }
  Ok(Page {
    keys,
    next_token: if truncated { next_token } else { None },
  })
}

/// Only keys generated by the historical workspace file uploader qualify.
/// Unknown keys are reported but never entered in the deletion ledger.
fn workspace_id(key: &str) -> Option<Uuid> {
  let rest = key.strip_prefix(PREFIX)?;
  let (id_str, filename) = rest.split_once('/')?;
  if filename.contains('/') {
    return None;
  }
  let id = Uuid::parse_str(id_str).ok()?;
  if id_str != id.to_string() {
    return None;
  }
  let (hash, extension) = match filename.split_once('.') {
    Some((hash, extension)) => (hash, Some(extension)),
    None => (filename, None),
  };
  if hash.len() != 64
    || !hash
      .bytes()
      .all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase())
  {
    return None;
  }
  if let Some(extension) = extension {
    if extension.is_empty() || !extension.bytes().all(|byte| byte.is_ascii_alphanumeric()) {
      return None;
    }
  }
  Some(id)
}

async fn tracked(db: &PgPool, key: &str) -> anyhow::Result<bool> {
  Ok(
    sqlx::query_scalar::<_, bool>(
      "SELECT EXISTS (SELECT 1 FROM files WHERE object_key = $1) \
      OR EXISTS (SELECT 1 FROM pending_file_uploads WHERE object_key = $1)",
    )
    .bind(key)
    .fetch_one(db)
    .await?,
  )
}

async fn backfill_key(db: &PgPool, id: Uuid, key: &str) -> anyhow::Result<bool> {
  let mut tx = db.begin().await?;
  store::lock_file_object_key(&mut tx, key).await?;
  let already_tracked: bool = sqlx::query_scalar(
    "SELECT EXISTS (SELECT 1 FROM files WHERE object_key = $1) \
      OR EXISTS (SELECT 1 FROM pending_file_uploads WHERE object_key = $1)",
  )
  .bind(key)
  .fetch_one(&mut *tx)
  .await?;
  if already_tracked {
    return Ok(false);
  }
  // The existing GC waits at least 30 days from this insertion and checks the
  // real object age before deleting. No object is deleted by this command.
  store::record_pending_file_upload_tx(&mut tx, id, key, 0).await?;
  tx.commit().await?;
  Ok(true)
}

pub async fn run(db: &PgPool, storage: &S3Config, backfill: bool) -> anyhow::Result<()> {
  run_prefix(db, storage, PREFIX, PAGE_SIZE, backfill).await
}

async fn run_prefix(
  db: &PgPool,
  storage: &S3Config,
  prefix: &str,
  page_size: u16,
  backfill: bool,
) -> anyhow::Result<()> {
  let http = reqwest::Client::builder()
    .timeout(Duration::from_secs(30))
    .build()?;
  let mut cursor: Option<String> = None;
  let mut seen = HashSet::new();
  let mut pages = 0usize;
  let mut candidates = 0usize;
  let mut inserted = 0usize;
  loop {
    pages += 1;
    if pages > 100_000 {
      bail!("S3 listing exceeded 100,000 pages");
    }
    let url = storage.presign_list_objects_v2(prefix, cursor.as_deref(), page_size);
    let mut response = http
      .get(url)
      .send()
      .await
      .context("S3 ListObjectsV2 request failed")?
      .error_for_status()
      .context("S3 ListObjectsV2 returned an error")?;
    let mut body = Vec::new();
    while let Some(chunk) = response.chunk().await? {
      if body.len() + chunk.len() > MAX_PAGE_BYTES {
        bail!("S3 list response is too large");
      }
      body.extend_from_slice(&chunk);
    }
    let xml = std::str::from_utf8(&body).context("S3 list response is not UTF-8")?;
    let page = parse_page(xml, prefix)?;
    for key in page.keys {
      if !key.starts_with(prefix) {
        bail!("S3 returned an object outside the requested prefix");
      }
      let Some(id) = workspace_id(&key) else {
        println!("{}", json!({"kind":"unexpected_key","key":key}));
        continue;
      };
      if !tracked(db, &key).await? {
        candidates += 1;
        let did_insert = backfill && backfill_key(db, id, &key).await?;
        if did_insert {
          inserted += 1;
        }
        println!(
          "{}",
          json!({"kind":"legacy_orphan","key":key,"workspace_id":id,"backfilled":did_insert})
        );
      }
    }
    match page.next_token {
      Some(next) => {
        if !seen.insert(next.clone()) {
          bail!("S3 repeated a continuation token");
        }
        cursor = Some(next);
      }
      None => break,
    }
  }
  println!(
    "{}",
    json!({"kind":"summary","mode":if backfill { "backfill" } else { "dry-run" },"pages":pages,"candidates":candidates,"backfilled":inserted})
  );
  Ok(())
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn list_parser_rejects_wrong_prefix_and_missing_cursor() {
    let xml = "<ListBucketResult><Prefix>workspaces/</Prefix><IsTruncated>true</IsTruncated><Contents><Key>workspaces/a</Key></Contents><NextContinuationToken>next</NextContinuationToken></ListBucketResult>";
    assert_eq!(
      parse_page(xml, PREFIX).unwrap(),
      Page {
        keys: vec!["workspaces/a".into()],
        next_token: Some("next".into())
      }
    );
    assert!(
      parse_page(
        &xml.replace("<Prefix>workspaces/", "<Prefix>avatars/"),
        PREFIX
      )
      .is_err()
    );
    assert!(
      parse_page(
        &xml.replace("<NextContinuationToken>next</NextContinuationToken>", ""),
        PREFIX
      )
      .is_err()
    );
  }

  #[test]
  fn only_generated_workspace_keys_qualify() {
    let key = format!("workspaces/{}/{}.png", Uuid::nil(), "a".repeat(64));
    assert_eq!(workspace_id(&key), Some(Uuid::nil()));
    assert_eq!(workspace_id(&key.replace("workspaces/", "avatars/")), None);
    assert_eq!(workspace_id(&format!("{key}/other")), None);
  }

  #[tokio::test]
  #[ignore = "requires local PostgreSQL and RustFS"]
  async fn historical_audit_is_dry_by_default_and_backfill_is_idempotent() {
    let database_url = std::env::var("DATABASE_URL").expect("DATABASE_URL");
    let db = PgPool::connect(&database_url).await.unwrap();
    let storage = S3Config::from_env().expect("S3 configuration");
    let http = reqwest::Client::new();
    let id = Uuid::new_v4();
    let prefix = format!("workspaces/{id}/");
    let keys = [
      format!("{prefix}{}.png", "a".repeat(64)),
      format!("{prefix}{}", "b".repeat(64)),
    ];
    for key in &keys {
      let sent = http
        .put(storage.presign_put_server(key).url)
        .body("test")
        .send()
        .await
        .unwrap();
      assert!(sent.status().is_success(), "PUT: {}", sent.status());
    }
    let result = async {
      let first = http
        .get(storage.presign_list_objects_v2(&prefix, None, 1))
        .send()
        .await
        .unwrap();
      assert!(first.status().is_success(), "list: {}", first.status());
      let first = parse_page(&first.text().await.unwrap(), &prefix).unwrap();
      assert_eq!(first.keys.len(), 1);
      let second = http
        .get(storage.presign_list_objects_v2(&prefix, first.next_token.as_deref(), 1))
        .send()
        .await
        .unwrap();
      assert!(
        second.status().is_success(),
        "continuation: {}",
        second.status()
      );
      let second = parse_page(&second.text().await.unwrap(), &prefix).unwrap();
      assert_eq!(second.keys.len(), 1);
      assert_ne!(first.keys, second.keys);
      run_prefix(&db, &storage, &prefix, 1, false).await.unwrap();
      for key in &keys {
        assert!(!tracked(&db, key).await.unwrap());
      }
      run_prefix(&db, &storage, &prefix, 1, true).await.unwrap();
      for key in &keys {
        assert!(tracked(&db, key).await.unwrap());
      }
      run_prefix(&db, &storage, &prefix, 1, true).await.unwrap();
      let count: i64 =
        sqlx::query_scalar("SELECT count(*) FROM pending_file_uploads WHERE workspace_id = $1")
          .bind(id)
          .fetch_one(&db)
          .await
          .unwrap();
      assert_eq!(count, 2);
    }
    .await;
    for key in &keys {
      http
        .delete(storage.presign_delete(key))
        .send()
        .await
        .unwrap();
    }
    sqlx::query("DELETE FROM pending_file_uploads WHERE workspace_id = $1")
      .bind(id)
      .execute(&db)
      .await
      .unwrap();
    result
  }
}
