// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/document.dart';
import 'api/pdf.dart';
import 'api/render.dart';
import 'api/simple.dart';
import 'api/store.dart';
import 'api/zip.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MicaDocumentPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MicaStorePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore;

  @protected
  MicaDocument
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument(
    dynamic raw,
  );

  @protected
  MicaStore
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore(
    dynamic raw,
  );

  @protected
  MicaDocument
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument(
    dynamic raw,
  );

  @protected
  MicaStore
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore(
    dynamic raw,
  );

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  MicaDocument
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument(
    dynamic raw,
  );

  @protected
  MicaStore
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  MicaDocument
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument(
    dynamic raw,
  );

  @protected
  MicaStore
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore(
    dynamic raw,
  );

  @protected
  CloneViewResult dco_decode_box_autoadd_clone_view_result(dynamic raw);

  @protected
  LocalVersion dco_decode_box_autoadd_local_version(dynamic raw);

  @protected
  LocalView dco_decode_box_autoadd_local_view(dynamic raw);

  @protected
  LocalWorkspace dco_decode_box_autoadd_local_workspace(dynamic raw);

  @protected
  SyncCursor dco_decode_box_autoadd_sync_cursor(dynamic raw);

  @protected
  CloneViewResult dco_decode_clone_view_result(dynamic raw);

  @protected
  DocUpdate dco_decode_doc_update(dynamic raw);

  @protected
  FolderExportImage dco_decode_folder_export_image(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DocUpdate> dco_decode_list_doc_update(dynamic raw);

  @protected
  List<FolderExportImage> dco_decode_list_folder_export_image(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<LocalVersion> dco_decode_list_local_version(dynamic raw);

  @protected
  List<LocalView> dco_decode_list_local_view(dynamic raw);

  @protected
  List<LocalWorkspace> dco_decode_list_local_workspace(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<StoreZipEntry> dco_decode_list_store_zip_entry(dynamic raw);

  @protected
  List<ZipAsset> dco_decode_list_zip_asset(dynamic raw);

  @protected
  LocalVersion dco_decode_local_version(dynamic raw);

  @protected
  LocalView dco_decode_local_view(dynamic raw);

  @protected
  LocalWorkspace dco_decode_local_workspace(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  MicaDocument?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument(
    dynamic raw,
  );

  @protected
  MicaStore?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore(
    dynamic raw,
  );

  @protected
  CloneViewResult? dco_decode_opt_box_autoadd_clone_view_result(dynamic raw);

  @protected
  LocalVersion? dco_decode_opt_box_autoadd_local_version(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  (PlatformInt64, PlatformInt64) dco_decode_record_i_64_i_64(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  StoreZipEntry dco_decode_store_zip_entry(dynamic raw);

  @protected
  SyncCursor dco_decode_sync_cursor(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  ZipAsset dco_decode_zip_asset(dynamic raw);

  @protected
  MicaDocument
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument(
    SseDeserializer deserializer,
  );

  @protected
  MicaStore
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore(
    SseDeserializer deserializer,
  );

  @protected
  MicaDocument
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument(
    SseDeserializer deserializer,
  );

  @protected
  MicaStore
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  MicaDocument
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument(
    SseDeserializer deserializer,
  );

  @protected
  MicaStore
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  MicaDocument
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument(
    SseDeserializer deserializer,
  );

  @protected
  MicaStore
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore(
    SseDeserializer deserializer,
  );

  @protected
  CloneViewResult sse_decode_box_autoadd_clone_view_result(
    SseDeserializer deserializer,
  );

  @protected
  LocalVersion sse_decode_box_autoadd_local_version(
    SseDeserializer deserializer,
  );

  @protected
  LocalView sse_decode_box_autoadd_local_view(SseDeserializer deserializer);

  @protected
  LocalWorkspace sse_decode_box_autoadd_local_workspace(
    SseDeserializer deserializer,
  );

  @protected
  SyncCursor sse_decode_box_autoadd_sync_cursor(SseDeserializer deserializer);

  @protected
  CloneViewResult sse_decode_clone_view_result(SseDeserializer deserializer);

  @protected
  DocUpdate sse_decode_doc_update(SseDeserializer deserializer);

  @protected
  FolderExportImage sse_decode_folder_export_image(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DocUpdate> sse_decode_list_doc_update(SseDeserializer deserializer);

  @protected
  List<FolderExportImage> sse_decode_list_folder_export_image(
    SseDeserializer deserializer,
  );

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<LocalVersion> sse_decode_list_local_version(
    SseDeserializer deserializer,
  );

  @protected
  List<LocalView> sse_decode_list_local_view(SseDeserializer deserializer);

  @protected
  List<LocalWorkspace> sse_decode_list_local_workspace(
    SseDeserializer deserializer,
  );

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<StoreZipEntry> sse_decode_list_store_zip_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<ZipAsset> sse_decode_list_zip_asset(SseDeserializer deserializer);

  @protected
  LocalVersion sse_decode_local_version(SseDeserializer deserializer);

  @protected
  LocalView sse_decode_local_view(SseDeserializer deserializer);

  @protected
  LocalWorkspace sse_decode_local_workspace(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  MicaDocument?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument(
    SseDeserializer deserializer,
  );

  @protected
  MicaStore?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore(
    SseDeserializer deserializer,
  );

  @protected
  CloneViewResult? sse_decode_opt_box_autoadd_clone_view_result(
    SseDeserializer deserializer,
  );

  @protected
  LocalVersion? sse_decode_opt_box_autoadd_local_version(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  (PlatformInt64, PlatformInt64) sse_decode_record_i_64_i_64(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  StoreZipEntry sse_decode_store_zip_entry(SseDeserializer deserializer);

  @protected
  SyncCursor sse_decode_sync_cursor(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  ZipAsset sse_decode_zip_asset(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument(
    MicaDocument self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore(
    MicaStore self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument(
    MicaDocument self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore(
    MicaStore self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument(
    MicaDocument self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore(
    MicaStore self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument(
    MicaDocument self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore(
    MicaStore self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_clone_view_result(
    CloneViewResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_local_version(
    LocalVersion self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_local_view(
    LocalView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_local_workspace(
    LocalWorkspace self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sync_cursor(
    SyncCursor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_clone_view_result(
    CloneViewResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_doc_update(DocUpdate self, SseSerializer serializer);

  @protected
  void sse_encode_folder_export_image(
    FolderExportImage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_doc_update(
    List<DocUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_folder_export_image(
    List<FolderExportImage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_local_version(
    List<LocalVersion> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_local_view(
    List<LocalView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_local_workspace(
    List<LocalWorkspace> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_store_zip_entry(
    List<StoreZipEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_zip_asset(List<ZipAsset> self, SseSerializer serializer);

  @protected
  void sse_encode_local_version(LocalVersion self, SseSerializer serializer);

  @protected
  void sse_encode_local_view(LocalView self, SseSerializer serializer);

  @protected
  void sse_encode_local_workspace(
    LocalWorkspace self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument(
    MicaDocument? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore(
    MicaStore? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_clone_view_result(
    CloneViewResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_local_version(
    LocalVersion? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_i_64_i_64(
    (PlatformInt64, PlatformInt64) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_store_zip_entry(StoreZipEntry self, SseSerializer serializer);

  @protected
  void sse_encode_sync_cursor(SyncCursor self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_zip_asset(ZipAsset self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaDocument(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMicaStore(
    int ptr,
  );
}
