//! CommonMark compliance scoreboard (roadmap P3): run the official spec's
//! 652 markdown→HTML examples through `import_markdown` + `export_html` and
//! report the pass rate per section. The score is a *measurement*, not a
//! gate — the only assertion is a regression floor so the number can never
//! silently drop.
//!
//! Regenerate the human-readable report after engine changes:
//!   GEN_SCOREBOARD=1 cargo test -p mica-markdown --test commonmark_scoreboard
//! (writes docs/commonmark-scoreboard.md at the repo root)

use std::collections::BTreeMap;

use mica_markdown::{export_html, import_markdown};
use serde_json::Value;

/// Passing examples must never decrease. Raise this when the engine improves
/// (P4 work); the per-section detail lives in docs/commonmark-scoreboard.md.
const BASELINE_PASS: usize = 620; // 96.4% of 643 — GFM dialect, 2026-06-05

/// CommonMark examples our GFM target dialect intentionally breaks —
/// cmark-gfm with extensions enabled fails these identically:
/// - 608/611/612: bare URL/email autolinks (GFM links them, CommonMark
///   wants plain text);
/// - 170–175: the tagfilter escapes `<script>`/`<style>`/`<textarea>`
///   blocks that CommonMark passes through raw (security wins).
const GFM_DIALECT_WAIVERS: &[u64] = &[608, 611, 612, 170, 171, 172, 173, 174, 175];

fn normalize(html: &str) -> String {
  // The official runner compares exact HTML; we only forgive trailing
  // whitespace/newlines so formatting of the final line break can't flip a
  // result.
  html.trim_end().to_string()
}

#[test]
fn commonmark_scoreboard() {
  let spec_path = format!(
    "{}/tests/fixtures/commonmark-spec-0.31.2.json",
    env!("CARGO_MANIFEST_DIR")
  );
  let examples: Vec<Value> =
    serde_json::from_str(&std::fs::read_to_string(spec_path).unwrap()).unwrap();

  let mut per_section: BTreeMap<String, (usize, usize)> = BTreeMap::new();
  let mut passed = 0usize;

  let mut waived = 0usize;
  for ex in &examples {
    if GFM_DIALECT_WAIVERS.contains(&ex["example"].as_u64().unwrap()) {
      waived += 1;
      continue;
    }
    let md = ex["markdown"].as_str().unwrap();
    let expected = ex["html"].as_str().unwrap();
    let section = ex["section"].as_str().unwrap().to_string();
    let got = export_html(&import_markdown(md, "root")).unwrap_or_default();
    let ok = normalize(&got) == normalize(expected);
    let entry = per_section.entry(section).or_insert((0, 0));
    entry.1 += 1;
    if ok {
      entry.0 += 1;
      passed += 1;
    }
  }

  let total = examples.len() - waived;
  let mut report = String::new();
  report.push_str("# CommonMark 0.31.2 scoreboard\n\n");
  report.push_str(
    "Generated by `GEN_SCOREBOARD=1 cargo test -p mica-markdown --test \
     commonmark_scoreboard`.\nMeasures the `import_markdown` → `export_html` \
     pipeline against the official spec\nexamples (exact-match HTML, \
     trailing whitespace forgiven). The number is a\nbaseline for P4 — see \
     docs/editor-engine.md Milestone 8.\n\n",
  );
  report.push_str(&format!(
    "**Total: {passed}/{total} ({:.1}%)** — {waived} GFM dialect waivers \
     (bare autolinks, tagfilter) excluded.\n\n",
    100.0 * passed as f64 / total as f64
  ));
  report.push_str("| Section | Passed | Total | % |\n|---|---|---|---|\n");
  for (section, (ok, n)) in &per_section {
    report.push_str(&format!(
      "| {section} | {ok} | {n} | {:.0}% |\n",
      100.0 * *ok as f64 / *n as f64
    ));
  }

  println!("{report}");

  if std::env::var("GEN_SCOREBOARD").is_ok() {
    let out = format!("{}/../../docs/commonmark-scoreboard.md", env!("CARGO_MANIFEST_DIR"));
    std::fs::write(out, &report).unwrap();
  }

  assert!(
    passed >= BASELINE_PASS,
    "CommonMark pass count regressed: {passed} < baseline {BASELINE_PASS}"
  );
}
